query GetAllBuildings {
  buildings {
    id
    name
  }
}

query GetBuildingById($id: Int!) {
  building(key: {id: $id}) {
    id
    name
  }
}

mutation CreateBuilding($id: Int!, $name: String!) {
  building_insert(data: {
    id: $id
    name: $name
  })
}

query GetBuildingParameters($buildingId: Int!) {
  buildingParameterss(where: {building: {id: {eq: $buildingId}}}) {
    climate
    floorArea
    buildingType
    envelope
    isAC
  }
}

mutation CreateBuildingParameters($id: Int!, $buildingId: Int!, $climate: Climate!, $floorArea: String!, $buildingType: BuildingType!, $envelope: EnvelopeType!, $isAC: Boolean!) {
  buildingParameters_insert(data: {
    id: $id
    building: {id: $buildingId}
    climate: $climate
    floorArea: $floorArea
    buildingType: $buildingType
    envelope: $envelope
    isAC: $isAC
  })
}

