query GetWindowSizes($buildingParametersId: UUID!) @auth(level: PUBLIC) {
  windowSizes(where: { buildingParameters: { id: { eq: $buildingParametersId } } }) {
    id
    area
    energyResult {
      cooling
      heating
      total
      carbon
      cost
    }
  }
}

query GetInsulationRoofs($buildingParametersId: UUID!) @auth(level: PUBLIC) {
  insulationRoofs(where: { buildingParameters: { id: { eq: $buildingParametersId } } }) {
    id
    type
    thickness
    rValue
    energyResult {
      cooling
      heating
      total
      carbon
      cost
    }
  }
}

query GetInsulationWalls($buildingParametersId: UUID!) @auth(level: PUBLIC) {
  insulationWalls(where: { buildingParameters: { id: { eq: $buildingParametersId } } }) {
    id
    type
    thickness
    rValue
    energyResult {
      cooling
      heating
      total
      carbon
      cost
    }
  }
}

query GetWindowGlazings($buildingParametersId: UUID!) @auth(level: PUBLIC) {
  windowGlazings(where: { buildingParameters: { id: { eq: $buildingParametersId } } }) {
    id
    type
    rValue
    shgc
    energyResult {
      cooling
      heating
      total
      carbon
      cost
    }
  }
}

query GetOrientations($buildingParametersId: UUID!) @auth(level: PUBLIC) {
  orientations(where: { buildingParameters: { id: { eq: $buildingParametersId } } }) {
    id
    direction
    energyResult {
      cooling
      heating
      total
      carbon
      cost
    }
  }
}

query GetOccupancies($buildingParametersId: UUID!) @auth(level: PUBLIC) {
  occupancies(where: { buildingParameters: { id: { eq: $buildingParametersId } } }) {
    id
    numberOfPeople
    energyResult {
      cooling
      heating
      total
      carbon
      cost
    }
  }
}

query GetWindowShadings($buildingParametersId: UUID!) @auth(level: PUBLIC) {
  windowShadings(where: { buildingParameters: { id: { eq: $buildingParametersId } } }) {
    id
    type
    isExternal
    energyResult {
      cooling
      heating
      total
      carbon
      cost
    }
  }
}
