mutation UpdateBuilding(
  $id: UUID!,
  $name: String!
) @auth(level: PUBLIC) {
  building_update(
    key: { id: $id }
    data: {
      name: $name
    }
  )
}

mutation UpdateBuildingParameters(
  $id: UUID!,
  $climate: Climate!,
  $floorArea: String!,
  $buildingType: BuildingType!,
  $envelope: EnvelopeType!,
  $isAC: Boolean!
) @auth(level: PUBLIC) {
  buildingParameters_update(
    key: { id: $id }
    data: {
      climate: $climate
      floorArea: $floorArea
      buildingType: $buildingType
      envelope: $envelope
      isAC: $isAC
    }
  )
}

mutation UpdateInsulationRoof(
  $id: UUID!,
  $type: String!,
  $thickness: Float!,
  $rValue: Float!
) @auth(level: PUBLIC) {
  insulationRoof_update(
    key: { id: $id }
    data: {
      type: $type
      thickness: $thickness
      rValue: $rValue
    }
  )
}

mutation UpdateInsulationWall(
  $id: UUID!,
  $type: String!,
  $thickness: Float!,
  $rValue: Float!
) @auth(level: PUBLIC) {
  insulationWall_update(
    key: { id: $id }
    data: {
      type: $type
      thickness: $thickness
      rValue: $rValue
    }
  )
}

mutation UpdateWindowSize(
  $id: UUID!,
  $area: Float!
) @auth(level: PUBLIC) {
  windowSize_update(
    key: { id: $id }
    data: {
      area: $area
    }
  )
}

mutation UpdateWindowGlazing(
  $id: UUID!,
  $type: String!,
  $rValue: Float!,
  $shgc: Float!
) @auth(level: PUBLIC) {
  windowGlazing_update(
    key: { id: $id }
    data: {
      type: $type
      rValue: $rValue
      shgc: $shgc
    }
  )
}

mutation UpdateOrientation(
  $id: UUID!,
  $direction: String!
) @auth(level: PUBLIC) {
  orientation_update(
    key: { id: $id }
    data: {
      direction: $direction
    }
  )
}

mutation UpdateOccupancy(
  $id: UUID!,
  $numberOfPeople: Int!
) @auth(level: PUBLIC) {
  occupancy_update(
    key: { id: $id }
    data: {
      numberOfPeople: $numberOfPeople
    }
  )
}

mutation UpdateWindowShading(
  $id: UUID!,
  $type: String!,
  $isExternal: Boolean!
) @auth(level: PUBLIC) {
  windowShading_update(
    key: { id: $id }
    data: {
      type: $type
      isExternal: $isExternal
    }
  )
}

mutation UpdateEnergyResult(
  $id: UUID!,
  $improvementType: String!,
  $cooling: Float!,
  $heating: Float!,
  $total: Float!,
  $carbon: Float!,
  $cost: Float!
) @auth(level: PUBLIC) {
  energyResult_update(
    key: { id: $id }
    data: {
      improvementType: $improvementType
      cooling: $cooling
      heating: $heating
      total: $total
      carbon: $carbon
      cost: $cost
    }
  )
}
