enum Climate {
  TROPICAL
  DRY_ARID_SEMIARID
  TEMPERATE
  CONTINENTAL
  POLAR_ALPINE
}

enum BuildingType {
  RESIDENTIAL
  OFFICE
  HOTEL
  GOVERNMENTAL
  SCHOOL
  HOSPITAL
  RETAIL
  AGED_CARE
  INDUSTRIAL
}

enum EnvelopeType {
  HIGH_MASS
  LOW_MASS
  GLAZED
}

type Building @table {
  id: Int!
  name: String!
}

type BuildingParameters @table {
  building: Building!

  climate: Climate!
  floorArea: String!
  buildingType: BuildingType!
  envelope: EnvelopeType!
  isAC: Boolean!
}

type Improvements @table {
  building: Building!
  name: String!
}

type InsulationRoof @table {
  improvements: Improvements!

  type: String!
  thickness: Int!
  rValue: Float!
}

type InsulationWall @table {
  improvements: Improvements!

  type: String!
  thickness: Int!
  rValue: Float!
}

type WindowSize @table {
  improvements: Improvements!

  area: Float!
}

type WindowGlazing @table {
  improvements: Improvements!

  type: String!
  rValue: Float!
  shgc: Float!
}

type Orientation @table {
  improvements: Improvements!

  direction: String!
}

type Occupancy @table {
  improvements: Improvements!

  numberOfPeople: Int!
}

type WindowShading @table {
  improvements: Improvements!

  type: String!
  isExternal: Boolean!
}

type EnergyResult @table {
  building: Building!
  improvements: Improvements!

  cooling: Float!
  heating: Float!
  total: Float!
  carbon: Float!
  cost: Float!
}
